export const userSagaActions = {
  SIGN_IN: 'SIGN_IN',
}

export const categorySagaActions = {
  ADD_CATEGORY: 'ADD_CATEGORY',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  EDIT_CATEGORIES: 'EDIT_CATEGORIES',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
}

export const productSagaActions = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
}

export const editCategorySagaActions = {
  EDIT_ECATEGORY: 'EDIT_ECATEGORY',
  LOAD_ECATEGORY: 'LOAD_ECATEGORY',
}

export const editProductSagaActions = {
  EDIT_EPRODUCT: 'EDIT_EPRODUCT',
  LOAD_EPRODUCT: 'LOAD_EPRODUCT',
}
