/* Palette generated by Material Palette - materialpalette.com/light-green/teal */
export const COLORS = {
  darkPrimaryColor: {background: '#689F38'},
  defaultPrimaryColor: {background: '#8BC34A'},
  lightPrimaryColor: {background: '#DCEDC8'},
  textPrimaryColor: {color: '#212121'},
  accentColor: {background: '#009688'},
  primaryTextColor: {color: '#212121'},
  secondaryTextColor: {color: '#757575'},
  dividerColor: {borderColor: '#BDBDBD'},
}
